[id='ickle-query-syntax_{context}']
= Ickle query language syntax

The Ickle query language is subset of the link:https://en.wikipedia.org/wiki/Java_Persistence_Query_Language[JPQL] query language, with some extensions for full-text.

The parser syntax has some notable rules:

* Whitespace is not significant.
* Wildcards are not supported in field names.
* A field name or path must always be specified, as there is no default field.
* `&&` and `||` are accepted instead of `AND` or `OR` in both full-text and JPA predicates.
* `!` may be used instead of `NOT`.
* A missing boolean operator is interpreted as `OR`.
* String terms must be enclosed with either single or double quotes.
* Fuzziness and boosting are not accepted in arbitrary order; fuzziness always comes first.
* `!=` is accepted instead of `<>`.
* Boosting cannot be applied to `>`,`>=`,`<`,`\<=` operators. Ranges may be used to achieve the same result.

== Filtering operators

Ickle support many filtering operators that can be used for both indexed and non-indexed fields.

[%header%autowidth,cols="1,1,1",stripes=even]
|===
|Operator |Description |Example

|`in`
|Checks that the left operand is equal to one of the elements from the Collection of values given as argument.
|`FROM Book WHERE isbn IN ('ZZ', 'X1234')`

|`like`
|Checks that the left argument (which is expected to be a String) matches a wildcard pattern that follows the JPA rules.
|`FROM Book WHERE title LIKE '%Java%'`

|`=`
|Checks that the left argument is an exact match of the given value.
|`FROM Book WHERE name = 'Programming Java'`

|`!=`
|Checks that the left argument is different from the given value.
|`FROM Book WHERE language != 'English'`

|`>`
|Checks that the left argument is greater than the given value.
|`FROM Book WHERE price > 20`

|`>=`
|Checks that the left argument is greater than or equal to the given value.
|`FROM Book WHERE price >= 20`

|`<`
|Checks that the left argument is less than the given value.
|`FROM Book WHERE year < 2020`

|`\<=`
|Checks that the left argument is less than or equal to the given value.
|`FROM Book WHERE price  <= 50`

|`between`
|Checks that the left argument is between the given range limits.
|`FROM Book WHERE price BETWEEN 50 AND 100`
|===

== Boolean conditions

Combining multiple attribute conditions with logical conjunction (`and`) and disjunction (`or`) operators in order to
create more complex conditions is demonstrated in the following example. The well known operator precedence rule for
boolean operators applies here, so the order of the operators is irrelevant. Here `and`
operator still has higher priority than `or` even though `or` was invoked first.

[source,sql]
----
# match all books that have "Data Grid" in their title
# or have an author named "Manik" and their description contains "clustering"

FROM org.infinispan.sample.Book WHERE title LIKE '%Data Grid%' OR author.name = 'Manik' AND description like '%clustering%'
----

Boolean negation has highest precedence among logical operators and applies only to the next simple attribute condition.

[source,sql]
----
# match all books that do not have "Data Grid" in their title and are authored by "Manik"
FROM org.infinispan.sample.Book WHERE title != 'Data Grid' AND author.name = 'Manik'
----

== Nested conditions
Changing the precedence of logical operators is achieved with parenthesis:

[source,sql]
----
# match all books that have an author named "Manik" and their title contains
# "Data Grid" or their description contains "clustering"
FROM org.infinispan.sample.Book WHERE author.name = 'Manik' AND ( title like '%Data Grid%' OR description like '% clustering%')
----

== Projections with SELECT statements
In some use cases returning the whole domain object is overkill if only a small subset of the attributes are actually
used by the application, especially if the domain entity has embedded entities. The query language allows you to specify
a subset of attributes (or attribute paths) to return - the projection. If projections are used then the `QueryResult.list()`
will not return the whole domain entity but will return a `List` of `Object[]`, each slot in the array corresponding to
a projected attribute.

[source,sql]
----
# match all books that have "Data Grid" in their title or description
# and return only their title and publication year
SELECT title, publicationYear FROM org.infinispan.sample.Book WHERE title like '%Data Grid%' OR description like '%Data Grid%'
----

=== Project cache entry version
It is possible to project the cache entry version, using the `version` projection function.

[source,sql]
----
# return the title, publication year and the cache entry version
SELECT b.title, b.publicationYear, version(b) FROM org.infinispan.sample.Book b WHERE b.title like '%Data Grid%'
----

=== Project cache entry value
It is possible to project the cache entry value together with other projections.
It can be used for instance to project the cache entry value together with the cache entry version
in the same `Object[]` returned hit.

[source,sql]
----
# return the cache entry value and the cache entry version
SELECT b, version(b) FROM org.infinispan.sample.Book b WHERE b.title like '%Data Grid%'
----

[id='score_projection']
=== Project the score
If the query is indexed, it is possible to project the score obtained by each matching together with other projections.
It can be used for instance to project the cache entry value together with the score
in the same `Object[]` returned hit.

[source,sql]
----
# return the cache entry value and the the score of the matching
SELECT b, score(b) FROM org.infinispan.sample.Book b WHERE b.title like '%Data Grid%'
----

[discrete]
== Sorting
Ordering the results based on one or more attributes or attribute paths is done with the `ORDER BY` clause. If multiple sorting criteria
are specified, then the order will dictate their precedence.

[source,sql]
----
# match all books that have "Data Grid" in their title or description
# and return them sorted by the publication year and title
FROM org.infinispan.sample.Book WHERE title like '%Data Grid%' ORDER BY publicationYear DESC, title ASC
----

[id='ickle-query-syntax-nested-objects_joins_{context}']
== Nested objects joins

When multivalued link:{query_docs}#indexing-annotations-overview_indexing-caches[`NESTED` embedded entities] are defined on a parent entity,
it is possible to treat the parent / embedded relation as a one to many relation.
This means that the `join` operator can be used to select all the parent entities that contain an embedded
entity satisfying some conditions.
This is in general not possible if the embedded reference is marked as `FLATTENED`, because in this case the
embedded fields will be treated as (multivalued) parent entity fields.

=== Nested objects joins: example

Suppose there is a parent entity `Team` having `Player` as a multivalued nested embedded entity:

[source,java]
----
@Proto
@Indexed
public record Team(@Basic String name, @Embedded(structure = Structure.NESTED) List<Player> firstTeam, @Embedded(structure = Structure.FLATTENED) List<Player> replacements) {

   @ProtoSchema(includeClasses = {Team.class, Player.class}, schemaPackageName = "model")
   public interface TeamSchema extends GeneratedSchema {
      TeamSchema INSTANCE = new TeamSchemaImpl();
   }
}

@Proto
public record Player(@Basic String name, @Basic String color, @Basic Integer number) {
}
----

Given this mapping, the following query:

[source,sql]
----
select t.name from model.Team t join t.firstTeam p where (p.color ='red' AND p.number=7) or (p.color='blue' AND p.number=7)
----

will return all the teams present on the system having at least one player in the first team group
in turn having number 7 and color red or blue.

== Grouping and aggregation

{brandname} has the ability to group query results according to a set of grouping fields and construct aggregations of
the results from each group by applying an aggregation function to the set of values that fall into each group.
Grouping and aggregation can only be applied to projection queries (queries with one or more field in the SELECT clause).

The supported aggregations are: `avg`, `sum`, `count`, `max`, and `min`.

The set of grouping fields is specified with the `GROUP BY` clause and the order used for defining grouping fields is
not relevant. All fields selected in the projection must either be grouping fields
or else they must be aggregated using one of the grouping functions described below. A projection field can be
aggregated and used for grouping at the same time. A query that selects only grouping fields but no aggregation fields
is legal.
⁠
Example: Grouping Books by author and counting them.
[source,sql]
----
SELECT author, COUNT(title) FROM org.infinispan.sample.Book WHERE title LIKE '%engine%' GROUP BY author
----

[NOTE]
====
A projection query in which all selected fields have an aggregation function applied and no fields are used for
grouping is allowed. In this case the aggregations will be computed globally as if there was a single global group.
====

[discrete]
=== Aggregations
You can apply the following aggregation functions to a field:

.Index merge attributes
[%header,cols=2*]
|===
|Aggregation function
|Description

|`avg()`
| Computes the average of a set of numbers. Accepted values are primitive numbers and instances of `java.lang.Number`. The result is represented as `java.lang.Double`. If there are no non-null values the result is `null` instead.

|`count()`
|Counts the number of non-null rows and returns a `java.lang.Long`. If there are no non-null values the result is `0` instead.

|`max()`
|Returns the greatest value found. Accepted values must be instances of `java.lang.Comparable`. If there are no non-null values the result is `null` instead.

|`min()`
|Returns the smallest value found. Accepted values must be instances of `java.lang.Comparable`. If there are no non-null values the result is `null` instead.

|`sum()`
|Computes the sum of a set of Numbers. If there are no non-null values the result is `null` instead. The following table indicates the return type based on the specified field.

|===

.Table sum return type
|===
|Field Type |Return Type

|Integral (other than BigInteger)
|Long

|Float or Double
|Double

|BigInteger
|BigInteger

|BigDecimal
|BigDecimal
|===

[discrete]
=== Evaluation of queries with grouping and aggregation

Aggregation queries can include filtering conditions, like usual queries. Filtering can be performed in two stages: before
and after the grouping operation. All filter conditions defined before invoking the `groupBy()` method will be applied
before the grouping operation is performed, directly to the cache entries (not to the final projection). These filter
conditions can reference any fields of the queried entity type, and are meant to restrict the data set that is going to
be the input for the grouping stage. All filter conditions defined after invoking the `groupBy()` method will be applied to
the projection that results from the projection and grouping operation. These filter conditions can either reference any
of the `groupBy()` fields or aggregated fields. Referencing aggregated fields that are not specified in the select clause
is allowed; however, referencing non-aggregated and non-grouping fields is forbidden. Filtering in this phase will
reduce the amount of groups based on their properties. Sorting can also be specified similar to usual queries. The
ordering operation is performed after the grouping operation and can reference any of the `groupBy()` fields or aggregated
fields.

== DELETE statements

You can delete entities from {brandname} caches with the following syntax:

[source,sql,title="Delete Query in Ickle"]
----
DELETE FROM <entityName> [WHERE condition]
----

* Reference only single entities with `<entityName>`. DELETE queries cannot use joins.
* WHERE conditions are optional.

DELETE queries cannot use any of the following:

* Projections with SELECT statements
* Grouping and aggregation
* ORDER BY clauses

[TIP]
====
Invoke the `Query.executeStatement()` method to execute DELETE statements.
====

== UPDATE statements

You can update entities in {brandname} caches with the following syntax:

[source,sql,title="Update Query in Ickle"]
----
UPDATE FROM <entityName> <operation> [,<operation>]* [WHERE condition]
----

Where `<operation>` is one of:

* `SET <field> = <expression>` — assign a new value to a field.
* `ADD <field> = <expression>` — add values to a collection field.
* `REMOVE <field> = <expression>` — remove values from a collection field.

* Reference only single entities with `<entityName>`. UPDATE queries cannot use joins.
* WHERE conditions are optional.

The `<expression>` on the right-hand side can be a constant, an arithmetic expression, a function call, a property reference, or a list:

* A single constant: `SET name = 'John'`
* An arithmetic expression: `SET age = age + 1`
* A function call: `SET name = upper(name)`
* A list of values in parentheses: `ADD tags = ('new', 'updated')`
* A list of values in square brackets: `ADD tags = ['new', 'updated']`

UPDATE queries cannot use any of the following:

* Projections with SELECT statements
* Grouping and aggregation
* ORDER BY clauses

[TIP]
====
Invoke the `Query.executeStatement()` method to execute UPDATE statements.
====

[id='update-expressions_{context}']
=== Expressions in UPDATE statements

The right-hand side of a `SET`, `ADD`, or `REMOVE` operation accepts expressions in addition to plain constants.
Expressions allow you to compute new values based on the current property values of the entity being updated.

[source,sql,title="Incrementing a numeric field"]
----
UPDATE FROM org.example.Account SET balance = balance + 100 WHERE id = 42
----

[source,sql,title="String concatenation with the + operator"]
----
UPDATE FROM org.example.Person SET fullName = firstName + ' ' + lastName WHERE id = 1
----

[source,sql,title="Using functions and named parameters"]
----
UPDATE FROM org.example.Product SET price = round(price * :factor) + :fee WHERE category = :cat
----

The following elements can appear in an expression:

* *Constants* — numeric literals (`42`, `3.14`), strings (`'hello'`), booleans (`true`, `false`), and `null`.
* *Property references* — the current value of any field on the entity, including nested paths (`address.city`).
* *Arithmetic operators* — `+`, `-`, `*`, `/`, `%` with standard precedence (multiplicative before additive, left-associative).
* *Unary minus* — `-expr` to negate an expression.
* *Parentheses* — to override the default operator precedence.
* *Function calls* — any of the built-in functions listed in link:#update-functions_{context}[Update functions].
* *Named parameters* — `:paramName` placeholders, set via `Query.setParameter()`.

[NOTE]
====
When the `+` operator has at least one `String` operand, it performs string concatenation instead of numeric addition.
All other operators require numeric operands.
====

[NOTE]
====
All operations in a single UPDATE statement are evaluated against the *original* entity state before any assignment is applied.
For example, `SET a = a + 1, b = a * 2` computes both expressions using the pre-update value of `a`.
====

[discrete]
==== Operator precedence

[%header,cols="1,1,2",stripes=even]
|===
|Precedence |Operator |Description

 |1 (highest)
 |`*`, `/`, `%`
 |Multiplication, division, modulo. Left-associative.

 |2
 |`+`, `-` (binary)
 |Addition (or string concatenation) and subtraction. Left-associative.

 |3 (lowest)
 |`+`, `-` (unary)
 |Unary plus or minus applied to a single operand.
|===

[discrete]
==== Null propagation

If any operand in an arithmetic expression is `null`, the result is `null`.
String concatenation with a `null` operand also yields `null`.
Division or modulo by zero is an error.

[discrete]
==== Type coercion

Arithmetic on two integral values (`byte`, `short`, `int`, `long`) produces a `long` result.
If either operand is floating-point, the result is a `double`.
The final value is coerced to the target property type on assignment.
For example, assigning a `double` value of `3.0` to an `int` field succeeds, but `3.5` is rejected.

[id='update-functions_{context}']
=== Update functions

{brandname} provides a set of built-in functions that can be called in UPDATE statement expressions.
Function names are case-insensitive.

[discrete]
==== Mathematical functions

[%header,cols="1,2,1,1",stripes=even]
|===
|Function |Description |Arguments |Returns

|`abs(n)`
 |Returns the absolute value of `n`.
 |`abs(-5)`
 |`5` (same integral/floating-point type as the argument)

|`round(n)`
 |Returns the nearest integer to `n`.
 |`round(3.7)`
 |`4` (long)

|`floor(n)`
 |Returns the largest integer less than or equal to `n`.
 |`floor(3.7)`
 |`3` (same type as the argument)

|`ceil(n)`
 |Returns the smallest integer greater than or equal to `n`.
 |`ceil(3.2)`
 |`4` (same type as the argument)

|`min(a, b)`
 |Returns the smaller of two values.
 |`min(3, 7)`
 |`3`

|`max(a, b)`
 |Returns the greater of two values.
 |`max(3, 7)`
 |`7`

|`power(a, b)`
 |Returns `a` raised to the power of `b`.
 |`power(2, 10)`
 |`1024`

|`sqrt(n)`
 |Returns the square root of `n`.
 |`sqrt(16)`
 |`4.0` (double)
|===

[discrete]
==== String functions

[%header,cols="1,2,1,1",stripes=even]
|===
|Function |Description |Arguments |Returns

|`concat(a, b, ...)`
 |Concatenates two or more values into a single string.
 |`concat('Hello, ', 'World')`
 |`'Hello, World'`

|`upper(s)`
 |Converts a string to upper case.
 |`upper('hello')`
 |`'HELLO'`

|`lower(s)`
 |Converts a string to lower case.
 |`lower('HELLO')`
 |`'hello'`

|`trim(s)`
 |Removes leading and trailing whitespace.
 |`trim('  padded  ')`
 |`'padded'`

|`length(s)`
 |Returns the number of characters in a string.
 |`length('hello')`
 |`5` (long)

|`substring(s, begin [, end])`
 |Returns a substring from index `begin` (inclusive) to `end` (exclusive). Indices are one-based.
 |`substring('Hello', 2, 4)`
 |`'el'`

|`replace(s, from, to)`
  |Replaces all occurrences of `from` with `to` in the string.
  |`replace('aaa', 'a', 'b')`
  |`'bbb'`
|===

[discrete]
==== Regexp functions

Regexp functions use Java regular-expression syntax (see `java.util.regex.Pattern`).
Patterns that are string literals in the query are compiled once and reused for all matching entities.

[%header,cols="1,2,1,1",stripes=even]
|===
|Function |Description |Arguments |Returns

|`regexp_like(s, pattern)`
|Returns `true` if the pattern matches anywhere in the string.
|`regexp_like('order-123', '\d+')`
|`true` (boolean)

|`regexp_replace(s, pattern, replacement)`
|Replaces all substrings matching the pattern with the replacement string.
|`regexp_replace('hello123', '\d+', 'X')`
|`'helloX'`

|`regexp_substr(s, pattern)`
|Returns the first substring matching the pattern, or `null` if no match.
|`regexp_substr('order-123', '\d+')`
|`'123'`

|`regexp_instr(s, pattern)`
  |Returns the one-based position of the first match, or `0` if no match.
  |`regexp_instr('hello123', '\d+')`
  |`6` (int)
|===

[discrete]
==== Date functions

All date functions accept a `java.util.Date` or `java.time.Instant` as the first argument and an integral amount as the second.

[%header,cols="1,2,1,1",stripes=even]
|===
|Function |Description |Arguments |Returns

|`addDays(d, n)`
|Adds or subtracts days.
|`addDays(dueDate, 7)`
|`Date` / `Instant`

|`addHours(d, n)`
|Adds or subtracts hours.
|`addHours(created, -24)`
|`Date` / `Instant`

|`addMinutes(d, n)`
|Adds or subtracts minutes.
|`addMinutes(start, 30)`
|`Date` / `Instant`

|`addMonths(d, n)`
|Adds or subtracts months.
|`addMonths(birthday, 1)`
|`Date` / `Instant`

|`addYears(d, n)`
|Adds or subtracts years.
|`addYears(expiry, 1)`
|`Date` / `Instant`

|`dateAdd(d, n, unit)`
|Generic date addition. The `unit` argument is a string: `'SECOND'`, `'MINUTE'`, `'HOUR'`, `'DAY'`, `'WEEK'`, `'MONTH'`, or `'YEAR'`.
|`dateAdd(due, 3, 'DAY')`
|`Date` / `Instant`
|===

[discrete]
==== Conversion functions

Conversion functions are useful for performing arithmetic on fields stored as strings or for changing the numeric type of a value.

[%header,cols="1,2,1,1",stripes=even]
|===
|Function |Description |Arguments |Returns

|`toLong(v)`
|Converts a number or numeric string to a long.
|`toLong('123')`
|`123` (long)

|`toDouble(v)`
|Converts a number or numeric string to a double.
|`toDouble('3.14')`
|`3.14` (double)

|`toString(v)`
|Converts any value to its string representation.
|`toString(42)`
|`'42'`
|===

include::proc_user_defined_functions.adoc[leveloffset=+1]

[role="_additional-resources"]
.Additional resources
* link:{javadocroot}/org/infinispan/query/dsl/Query.html#executeStatement()[org.infinispan.query.dsl.Query.executeStatement()]
