[id='role-mappers_{context}']
= Role and permission mappers

{brandname} security authorization uses the `PrincipalRoleMapper` API to map security entities, or principals, to the roles that you assign to users and groups.
The `RolePermissionMapper` API allows you to dynamically retrieve user roles and map roles to permissions.

This topic describes the role and permission mappers that {brandname} provides by default.
You can also create role and permission mappers with custom implementations of the `PrincipalRoleMapper` and `RolePermissionMapper` APIs.

Cluster role mapper:: Stores principal to role mappings in the cluster registry. This is the default role mapper and is automatically enabled in the {brandname} Server configuration.

Cluster permission mapper:: Stores role to permission mappings in the cluster registry and allows you to dynamically modify user roles and permissions. This is the default permission mapper and is automatically enabled in the {brandname} Server configuration. 

Identity role mapper:: Uses the principal name as the role name. The type or format of the principal name depends on the source. For example in an LDAP directory the principal name could be a Distinguished Name (DN).

Common name role mapper:: Uses the Common Name (CN) as the role name. You can use this role mapper with an LDAP directory that contains Distinguished Names (DN); for example `cn=managers,ou=people,dc=example,dc=com` maps to the `managers` role.

[role="_additional-resources"]
.Additional resources
* link:{javadocroot}/org/infinispan/security/package-summary.html[{brandname} Security API]
* link:{javadocroot}/org/infinispan/security/PrincipalRoleMapper.html[org.infinispan.security.PrincipalRoleMapper]
* link:{javadocroot}/org/infinispan/security/RolePermissionMapper.html[org.infinispan.security.RolePermissionMapper]
* link:{javadocroot}/org/infinispan/security/mappers/IdentityRoleMapper.html[org.infinispan.security.mappers.IdentityRoleMapper]
* link:{javadocroot}/org/infinispan/security/mappers/CommonNameRoleMapper.html[org.infinispan.security.mappers.CommonNameRoleMapper]
